# Generated by Django 3.1.7 on 2021-03-24 18:15

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('users', '0004_useradress'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='useradress',
            options={'verbose_name': 'Endereço', 'verbose_name_plural': 'Endereços'},
        ),
        migrations.AlterField(
            model_name='useradress',
            name='city',
            field=models.CharField(default='Guarapuava', max_length=30, verbose_name='Cidade'),
        ),
        migrations.AlterField(
            model_name='useradress',
            name='complement',
            field=models.CharField(blank=True, max_length=50, verbose_name='Complemento'),
        ),
        migrations.AlterField(
            model_name='useradress',
            name='district',
            field=models.CharField(max_length=30, verbose_name='Bairro'),
        ),
        migrations.AlterField(
            model_name='useradress',
            name='number',
            field=models.CharField(max_length=5, verbose_name='Número'),
        ),
        migrations.AlterField(
            model_name='useradress',
            name='state',
            field=models.CharField(default='Paraná', max_length=30, verbose_name='Estado'),
        ),
        migrations.AlterField(
            model_name='useradress',
            name='street',
            field=models.CharField(max_length=55, verbose_name='Rua'),
        ),
        migrations.AlterField(
            model_name='useradress',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Usuário'),
        ),
    ]
