# Generated by Django 3.1.7 on 2021-03-26 18:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0007_auto_20210326_1459'),
    ]

    operations = [
        migrations.AddField(
            model_name='useradress',
            name='name',
            field=models.CharField(default='null', max_length=30, verbose_name='Nome'),
            preserve_default=False,
        ),
    ]
