# Generated by Django 3.1.7 on 2021-03-23 18:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_auto_20210320_2138'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='MessageBox',
            new_name='Messages',
        ),
        migrations.AlterModelOptions(
            name='messages',
            options={'verbose_name': 'Mensagem', 'verbose_name_plural': 'Mensagens'},
        ),
    ]
