# Generated by Django 3.1.7 on 2021-04-05 14:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=55, verbose_name='categoria')),
            ],
        ),
        migrations.CreateModel(
            name='Products',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=55, verbose_name='Nome')),
                ('normal_price', models.CharField(max_length=10, verbose_name='Preço')),
                ('promotion_price', models.CharField(max_length=10, verbose_name='Preço promocional')),
                ('promotion', models.BooleanField(default=False, verbose_name='Em promoção')),
                ('picture', models.ImageField(upload_to='products/%Y/%m/', verbose_name='Imagem')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='products.category')),
            ],
        ),
    ]
