# Generated by Django 3.1.7 on 2021-04-05 14:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={'verbose_name': 'Categoria', 'verbose_name_plural': 'Categorias'},
        ),
        migrations.AlterModelOptions(
            name='products',
            options={'verbose_name': 'Produto', 'verbose_name_plural': 'Produtos'},
        ),
        migrations.AlterField(
            model_name='category',
            name='name',
            field=models.CharField(choices=[('Lanches', 'Lanches'), ('Bebidas', 'Bebidas'), ('Combos', 'Combos')], default='Lanches', max_length=55, verbose_name='categoria'),
        ),
    ]
